listnifty = [ "NIFTY REALTY", "NIFTY SERV SECTOR", "NIFTY 50", "NIFTY NEXT 50", "NIFTY100 LIQ 15", "NIFTY 100", "NIFTY 500", "NIFTY MIDCAP 50", "NIFTY MID LIQ 15", "NIFTY 200", "NIFTY BANK", "NIFTY AUTO", "NIFTY COMMODITIES", "NIFTY CONSUMPTION", "NIFTY CPSE", "NIFTY ENERGY", "NIFTY FIN SERVICE", "NIFTY FMCG", "NIFTY INFRA", "NIFTY IT", "NIFTY MEDIA", "NIFTY METAL", "NIFTY MNC", "NIFTY GROWSECT 15", "NIFTY50 VALUE 20", "NIFTY PHARMA", "NIFTY PSE", "NIFTY PSU BANK", "NIFTY PVT BANK" ]
for code in listnifty:
    print(code.replace(' ','%20'))
